import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import ClientSideToastContainer from "./ToastContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WordWave",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <Header />
          <ClientSideToastContainer />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
